on:
  push:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}:latest
  
permissions:
  packages: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create a Dockerfile
        run: |
          echo 'FROM ubuntu:18.04' > Dockerfile
          echo 'ENTRYPOINT echo "Hello, I am a huge image"' >> Dockerfile
          echo 'LABEL org.opencontainers.image.description "This image was built from commit ${{ github.sha }}"' >> Dockerfile
      - name: Build image
        run: docker build . -t ${IMAGE,,} # lowercase IMAGE

      - name: Login to ghcr.io
        run: docker login https://ghcr.io -u token --password-stdin <<< ${{ github.token }}

      - name: Publish image
        run: docker push ${IMAGE,,} # lowercase IMAGE
